//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacture
    {
        public System.DateTime mDateTime { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<double> ItemNO { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<double> RecipeSN1 { get; set; }
        public Nullable<double> ActualSN1 { get; set; }
        public Nullable<double> RecipeSN2 { get; set; }
        public Nullable<double> ActualSN2 { get; set; }
        public Nullable<double> RecipeSN3 { get; set; }
        public Nullable<double> ActualSN3 { get; set; }
        public Nullable<double> RecipeFMH { get; set; }
        public Nullable<double> ActualFMH { get; set; }
        public Nullable<double> RecipeFJJ { get; set; }
        public Nullable<double> ActualFJJ { get; set; }
        public Nullable<double> RecipeKF { get; set; }
        public Nullable<double> ActualKF { get; set; }
        public Nullable<double> RecipeWJJ1 { get; set; }
        public Nullable<double> ActualWJJ1 { get; set; }
        public Nullable<double> RecipeWJJ2 { get; set; }
        public Nullable<double> ActualWJJ2 { get; set; }
        public Nullable<double> RecipeDSL { get; set; }
        public Nullable<double> ActualDSL { get; set; }
        public Nullable<double> RecipeZSL { get; set; }
        public Nullable<double> ActualZSL { get; set; }
        public Nullable<double> RecipeXSL { get; set; }
        public Nullable<double> ActualXSL { get; set; }
        public Nullable<double> RecipeSZ { get; set; }
        public Nullable<double> ActualSZ { get; set; }
        public Nullable<double> RecipeSZ1 { get; set; }
        public Nullable<double> ActualSZ1 { get; set; }
        public Nullable<double> RecipeSHUI { get; set; }
        public Nullable<double> ActualSHUI { get; set; }
        public Nullable<double> RecipeOth1 { get; set; }
        public Nullable<double> ActualOth1 { get; set; }
        public Nullable<double> RecipeOth2 { get; set; }
        public Nullable<double> ActualOth2 { get; set; }
        public Nullable<double> RecipeSN4 { get; set; }
        public Nullable<double> ActualSN4 { get; set; }
        public Nullable<double> RecipeSZ2 { get; set; }
        public Nullable<double> ActualSZ2 { get; set; }
        public Nullable<System.DateTime> eDateTime { get; set; }
        public Nullable<double> mixtime { get; set; }
        public Nullable<long> v153_number { get; set; }
        public Nullable<double> HslDSL { get; set; }
        public Nullable<double> HslZSL { get; set; }
        public Nullable<double> HslXSL { get; set; }
        public Nullable<double> HslSZ { get; set; }
        public Nullable<double> HslSZ1 { get; set; }
        public Nullable<double> HslSZ2 { get; set; }
        public Nullable<double> HslST3 { get; set; }
        public Nullable<double> HslST4 { get; set; }
        public string mantype { get; set; }
        public Nullable<bool> bSlurry { get; set; }
        public string RecipeName { get; set; }
        public Nullable<double> Actual1 { get; set; }
        public Nullable<double> Actual2 { get; set; }
        public Nullable<double> Actual3 { get; set; }
        public Nullable<double> Actual4 { get; set; }
        public Nullable<double> Actual5 { get; set; }
        public Nullable<double> Actual6 { get; set; }
        public Nullable<double> Actual7 { get; set; }
        public Nullable<double> Actual8 { get; set; }
        public Nullable<double> Actual9 { get; set; }
        public Nullable<double> Actual10 { get; set; }
        public Nullable<double> Actual11 { get; set; }
        public Nullable<double> Actual12 { get; set; }
        public Nullable<double> Actual13 { get; set; }
        public Nullable<double> Actual14 { get; set; }
        public Nullable<double> Actual15 { get; set; }
        public Nullable<double> Actual16 { get; set; }
        public Nullable<double> DSLhst { get; set; }
        public Nullable<double> ZSLhst { get; set; }
        public Nullable<double> XSLhst { get; set; }
        public Nullable<double> SZhst { get; set; }
        public Nullable<double> SZ1hst { get; set; }
        public Nullable<bool> btx1 { get; set; }
        public Nullable<double> RecipeM17 { get; set; }
        public Nullable<double> RecipeM18 { get; set; }
        public Nullable<double> RecipeM19 { get; set; }
        public Nullable<double> RecipeM20 { get; set; }
        public Nullable<double> ActualM17 { get; set; }
        public Nullable<double> ActualM18 { get; set; }
        public Nullable<double> ActualM19 { get; set; }
        public Nullable<double> ActualM20 { get; set; }
        public Nullable<double> Actual17 { get; set; }
        public Nullable<double> Actual18 { get; set; }
        public Nullable<double> Actual19 { get; set; }
        public Nullable<double> Actual20 { get; set; }
        public Nullable<double> hslM17 { get; set; }
        public Nullable<double> hslM18 { get; set; }
        public Nullable<double> hslM19 { get; set; }
        public Nullable<double> hslM20 { get; set; }
    }
}
