//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutMaster
    {
        public int DeliveryID { get; set; }
        public string DeliveryName { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string RecipeNo { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> ItemNo { get; set; }
        public string TruckID { get; set; }
        public string ShipAdd { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string CompanyName { get; set; }
        public string ProjectCmpy { get; set; }
        public string ProjectPart { get; set; }
        public string StationName { get; set; }
        public Nullable<double> PlanCount { get; set; }
        public Nullable<double> EndCount { get; set; }
        public string FName { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> OutCount { get; set; }
        public string reserve2 { get; set; }
        public Nullable<int> reserve1 { get; set; }
        public Nullable<int> CementID { get; set; }
        public string CementName { get; set; }
        public string intensityLevel { get; set; }
        public string ksd { get; set; }
        public string kzd { get; set; }
        public string tld { get; set; }
        public string sljdj { get; set; }
        public string sszdlj { get; set; }
        public string WorkMethod { get; set; }
        public string Memo1 { get; set; }
        public string Memo2 { get; set; }
        public string dName { get; set; }
        public string TaskName { get; set; }
        public Nullable<bool> bSlurry { get; set; }
        public Nullable<double> SlurryQuantity { get; set; }
        public string SlurryRecipeNo { get; set; }
        public Nullable<double> TotalItemNo { get; set; }
        public Nullable<bool> noEven { get; set; }
        public string prjno { get; set; }
        public string lshao { get; set; }
    }
}
