//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        public int RecipeID { get; set; }
        public string RecipeName { get; set; }
        public Nullable<double> RecipeSN1 { get; set; }
        public Nullable<double> RecipeSN2 { get; set; }
        public Nullable<double> RecipeSN3 { get; set; }
        public Nullable<double> RecipeFMH { get; set; }
        public Nullable<double> RecipeFJJ { get; set; }
        public Nullable<double> RecipeKF { get; set; }
        public Nullable<double> RecipeWJJ1 { get; set; }
        public Nullable<double> RecipeWJJ2 { get; set; }
        public Nullable<double> RecipeDSL { get; set; }
        public Nullable<double> RecipeZSL { get; set; }
        public Nullable<double> RecipeXSL { get; set; }
        public Nullable<double> RecipeSZ { get; set; }
        public Nullable<double> RecipeSZ1 { get; set; }
        public Nullable<double> RecipeSHUI { get; set; }
        public Nullable<double> RecipeOth1 { get; set; }
        public Nullable<double> RecipeOth2 { get; set; }
        public Nullable<double> RecipeSN4 { get; set; }
        public Nullable<double> RecipeSZ2 { get; set; }
        public string intensityLevel { get; set; }
        public string ksd { get; set; }
        public string kzd { get; set; }
        public string tld { get; set; }
        public string sljdj { get; set; }
        public string sszdlj { get; set; }
        public Nullable<double> sjb { get; set; }
        public Nullable<double> sl { get; set; }
        public Nullable<double> bgmd { get; set; }
        public Nullable<double> OnOrder { get; set; }
        public string RecipeCodeERP { get; set; }
        public Nullable<bool> bwnrlsj { get; set; }
        public Nullable<double> RecipeM17 { get; set; }
        public Nullable<double> RecipeM18 { get; set; }
        public Nullable<double> RecipeM19 { get; set; }
        public Nullable<double> RecipeM20 { get; set; }
    }
}
