//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public int StationID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> planDate { get; set; }
        public Nullable<int> OutCount { get; set; }
        public Nullable<double> PlanCount { get; set; }
        public Nullable<double> EndCount { get; set; }
        public Nullable<double> DSL { get; set; }
        public Nullable<double> ZSL { get; set; }
        public Nullable<double> XSL { get; set; }
        public Nullable<double> SZ { get; set; }
        public Nullable<double> SZ1 { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCmpy { get; set; }
        public string ShipToAdd1 { get; set; }
        public string ShipToContact { get; set; }
        public string RecipeNo { get; set; }
        public string ProjectPart { get; set; }
        public string WorkMethod { get; set; }
        public Nullable<bool> ShipVia { get; set; }
        public Nullable<int> CementID { get; set; }
        public string Memo1 { get; set; }
        public string Memo2 { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<bool> Ustate { get; set; }
        public Nullable<double> SZ2 { get; set; }
        public string CustomerName { get; set; }
        public string TaskCodeERP { get; set; }
        public string prjno { get; set; }
        public string lshao { get; set; }
        public Nullable<double> DSLst { get; set; }
        public Nullable<double> ZSLst { get; set; }
        public Nullable<double> XSLst { get; set; }
        public Nullable<double> SZst { get; set; }
        public Nullable<double> SZ1st { get; set; }
        public string intensityLevelt { get; set; }
        public string tldt { get; set; }
    }
}
